'use client'

import { useRouter } from 'next/navigation'
import { Home, Users, Settings, Sliders, Terminal, Building, Clock, AlertCircle, Play, ShieldCheck, Database, Activity, FileText, Target, Grid } from 'lucide-react'

const navLinks = [
  { id: 'dashboard',  label: 'Dashboard',        icon: Home,       badge: null,  active: true, path: '/admin' },
  { id: 'config',     label: 'Configuration',    icon: Settings,   badge: null,  active: false, path: '/admin/configuration' },
  { id: 'spi-config', label: 'SPI Weight Config',icon: Target,     badge: null,  active: false, path: '/admin/spi-config' },
  { id: 'institution',label: 'Institution Settings',icon: Grid,    badge: null,  active: false, path: '/admin/institution' },
  { id: 'logs',       label: 'System Logs',      icon: Activity,   badge: null,  active: false, path: '/admin/configuration' },
]

import { PageHeader, StatCard, Card, Badge } from '@/components/ui'

const statCards = [
  { label: 'Total Users', value: '1,498', sub: 'Faculty + Students', icon: Users, tone: 'info' },
  { label: 'System Health', value: 'All Good', sub: 'Monitoring active', icon: ShieldCheck, tone: 'success' },
  { label: 'Active Sessions', value: '342', sub: 'Right now', icon: Activity, tone: 'brand' },
  { label: 'Pending Actions', value: '7', sub: 'Requires attention', icon: AlertCircle, tone: 'warning' },
]

const systemLogs = [
  { msg: 'New faculty account created — Dr. Suresh Iyer', time: '10 mins ago', icon: Users, tone: 'info' },
  { msg: 'SPI recalculation completed for CSE 2nd year', time: '1 hour ago', icon: Sliders, tone: 'brand' },
  { msg: '47 alerts generated by Alert Agent', time: '2 hours ago', icon: AlertCircle, tone: 'warning' },
  { msg: 'Bulk marks upload — OS Unit 3 — 240 records', time: '3 hours ago', icon: Database, tone: 'success' },
  { msg: 'NAAC report generated by Dean Verma', time: 'yesterday', icon: FileText, tone: 'gray' },
]

const quickActions = [
  { text: 'Configure SPI weights for next semester', icon: Sliders },
  { text: 'Add new branch or section', icon: Building },
  { text: 'Manage faculty subject assignments', icon: Users },
  { text: 'View full system logs', icon: Terminal },
]



export default function AdminDashboard() {
  const router = useRouter()

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <PageHeader 
          title="System Overview — April 2026" 
          description="All systems operational"
        />
        <button className="btn-secondary flex items-center gap-2">
          <Play size={14} /> Run Diagnostics
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
        {statCards.map((card, i) => (
          <StatCard
            key={i}
            label={card.label}
            value={card.value}
            hint={card.sub}
            icon={card.icon}
            tone={card.tone as any}
          />
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {/* Left Column - Logs */}
        <Card className="flex flex-col">
          <div className="flex items-center justify-between mb-4 pb-4 border-b border-line">
            <h3 className="font-semibold text-content flex items-center gap-2">
              <Terminal size={16} className="text-muted" /> Recent System Activity
            </h3>
            <button className="text-xs text-info hover:underline">View All</button>
          </div>
          <div className="space-y-4">
            {systemLogs.map((log, i) => (
              <div key={i} className="flex gap-4 items-start">
                <div className={`mt-0.5 text-${log.tone === 'gray' ? 'muted' : log.tone}`}>
                  <log.icon size={16} />
                </div>
                <div className="flex-1">
                  <p className="text-sm text-content font-medium">{log.msg}</p>
                  <p className="text-xs text-muted mt-0.5 flex items-center gap-1">
                    <Clock size={12} /> {log.time}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Right Column - Actions */}
        <Card className="flex flex-col">
          <div className="flex items-center justify-between mb-4 pb-4 border-b border-line">
            <h3 className="font-semibold text-content">Quick Configuration Actions</h3>
            <Settings size={15} className="text-muted" />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 flex-1">
            {quickActions.map((action, i) => (
              <button key={i} className="p-4 rounded-xl border border-line bg-surface hover:border-brand hover:shadow-sm transition-all text-left flex flex-col items-start gap-3 group">
                <div className="w-10 h-10 rounded-lg bg-surface-2 flex items-center justify-center text-muted group-hover:bg-brand group-hover:text-white transition-colors border border-line">
                  <action.icon size={20} />
                </div>
                <span className="text-sm font-medium text-content group-hover:text-brand transition-colors leading-snug">
                  {action.text}
                </span>
              </button>
            ))}
          </div>
        </Card>
      </div>
    </div>
  )
}

