export const mockMeetings = [
  {
    id: 1,
    title: "Meeting with Director",
    date: "2025-05-15",
    time: "11:00 AM",
    location: "Dean's Office",
    type: "Director",
    status: "upcoming",
    source: "agent",
    attendees: 2,
    notes: "Discuss departmental budget allocation for Q3.",
  },
  {
    id: 2,
    title: "Departmental Budget Review",
    date: "2025-05-12",
    time: "10:00 AM",
    location: "Conference Room A",
    type: "Faculty",
    status: "urgent",
    source: "manual",
    attendees: 8,
    notes: "Annual budget review with HODs.",
  },
  {
    id: 3,
    title: "Faculty Senate Session",
    date: "2025-05-13",
    time: "2:00 PM",
    location: "Senate Hall",
    type: "Senate",
    status: "upcoming",
    source: "manual",
    attendees: 15,
    notes: "Quarterly senate session — attendance mandatory.",
  },
  {
    id: 4,
    title: "PhD Thesis Defense Review",
    date: "2025-05-20",
    time: "3:00 PM",
    location: "Room 204",
    type: "Academic",
    status: "upcoming",
    source: "agent",
    attendees: 5,
    notes: "Review panel for two PhD candidates.",
  },
  {
    id: 5,
    title: "External Accreditation Meeting",
    date: "2025-05-28",
    time: "9:30 AM",
    location: "Board Room",
    type: "External",
    status: "upcoming",
    source: "manual",
    attendees: 10,
    notes: "Accreditation body visit — prepare all reports.",
  },
];

export const mockNotifications = [
  { id: 1, type: "reminder", title: "Meeting with Director in 2 days", description: "Scheduled for May 15 at 11:00 AM", time: "2 hours ago", read: false },
  { id: 2, type: "agent", title: "Agent added: PhD Thesis Review", description: "Added to May 20 at 3:00 PM", time: "5 hours ago", read: false },
  { id: 3, type: "deadline", title: "Budget report due tomorrow", description: "Submit to finance office by 5:00 PM", time: "Yesterday", read: true },
  { id: 4, type: "update", title: "Faculty Senate rescheduled", description: "Moved from May 12 to May 13", time: "2 days ago", read: true },
  { id: 5, type: "system", title: "Schedule synced", description: "All meetings synced successfully", time: "3 days ago", read: true },
];

export const mockDeanProfile = {
  name: "Dr. R. Sharma",
  initials: "DR",
  role: "Dean, Faculty of Engineering",
  department: "CSE Department",
};
