'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Home, Users, Settings, Sliders, Calendar, Terminal, Building, LogOut, Search, ChevronDown, Bell, CheckCircle, Clock, AlertCircle, Play, Settings2, ShieldCheck, Database, User, Activity, TrendingUp, Award, Grid, FileText, Target, Zap, BookOpen, Plug } from 'lucide-react'

const navLinks = [
  { id: 'dashboard',  label: 'Dashboard',        icon: Home,       badge: null,  active: true, path: '/dashboard/admin' },
  { id: 'config',     label: 'Configuration',    icon: Settings,   badge: null,  active: false, path: '/dashboard/admin/configuration' },
  { id: 'spi-config', label: 'SPI Weight Config',icon: Target,     badge: null,  active: false, path: '/dashboard/admin/spi-config' },
  { id: 'institution',label: 'Institution Settings',icon: Grid,    badge: null,  active: false, path: '/dashboard/admin/institution' },
  { id: 'logs',       label: 'System Logs',      icon: Activity,   badge: null,  active: false, path: '/dashboard/admin/configuration' },
]

const statCards = [
  { label: 'Total Users', value: '1,498', sub: 'Faculty + Students', icon: Users, bg: 'bg-blue-100', color: '#1A56DB', border: 'border-l-4 border-blue-500' },
  { label: 'System Health', value: 'All Good', sub: 'Monitoring active', icon: ShieldCheck, bg: 'bg-teal-100', color: '#0F766E', border: 'border-l-4 border-teal-500' },
  { label: 'Active Sessions', value: '342', sub: 'Right now', icon: ActivityIcon, bg: 'bg-purple-100', color: '#5B21B6', border: 'border-l-4 border-purple-500' },
  { label: 'Pending Actions', value: '7', sub: 'Requires attention', icon: AlertCircle, bg: 'bg-amber-100', color: '#D97706', border: 'border-l-4 border-amber-500' },
]

const systemLogs = [
  { msg: 'New faculty account created — Dr. Suresh Iyer', time: '10 mins ago', icon: Users, color: 'text-blue-500' },
  { msg: 'SPI recalculation completed for CSE 2nd year', time: '1 hour ago', icon: Sliders, color: 'text-purple-500' },
  { msg: '47 alerts generated by Alert Agent', time: '2 hours ago', icon: AlertCircle, color: 'text-amber-500' },
  { msg: 'Bulk marks upload — OS Unit 3 — 240 records', time: '3 hours ago', icon: Database, color: 'text-teal-500' },
  { msg: 'NAAC report generated by Dean Verma', time: 'yesterday', icon: FileTextIcon, color: 'text-gray-500' },
]

const quickActions = [
  { text: 'Configure SPI weights for next semester', icon: Sliders },
  { text: 'Add new branch or section', icon: Building },
  { text: 'Manage faculty subject assignments', icon: Users },
  { text: 'View full system logs', icon: Terminal },
]

// Simple local components since we can't import all dynamically
function ActivityIcon(props) {
  return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>;
}

function FileTextIcon(props) {
  return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><line x1="10" y1="9" x2="8" y2="9"></line></svg>;
}


export default function AdminDashboard() {
  const router = useRouter()
  const [activeNav, setActiveNav] = useState('dashboard')
  const [sidebarOpen, setSidebarOpen] = useState(true)

  return (
    <div className="flex h-screen bg-bg-base overflow-hidden font-sans">
      {/* SIDEBAR */}
      <aside className={`${sidebarOpen ? 'w-64' : 'w-0 overflow-hidden'} flex-shrink-0 bg-gray-900 text-gray-300 flex flex-col transition-all duration-300 shadow-xl z-20`}>
        <div className="p-5 border-b border-gray-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-gray-800 flex items-center justify-center text-white font-bold text-sm flex-shrink-0 border border-gray-700">
              AD
            </div>
            <div className="overflow-hidden">
              <p className="font-semibold text-sm text-white truncate">Admin · System</p>
              <p className="text-xs text-gray-500 truncate">Educator Analytics OS</p>
            </div>
          </div>
        </div>

        <nav className="flex-1 p-3 overflow-y-auto">
          {navLinks.map(link => (
            <button key={link.id} onClick={() => setActiveNav(link.id)} className={`nav-link w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all cursor-pointer mb-0.5 ${activeNav === link.id ? 'bg-gray-800 text-white' : 'hover:bg-gray-800/50 hover:text-white'}`}>
              <link.icon size={17} />
              <span className="flex-1 text-left">{link.label}</span>
            </button>
          ))}
        </nav>

        <div className="p-3 border-t border-gray-800">
          <button onClick={() => router.push('/login')} className="nav-link w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-all cursor-pointer text-red-400 hover:bg-red-900/30 hover:text-red-300">
            <LogOut size={17} />
            <span className="flex-1 text-left">Switch Role</span>
          </button>
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <header className="bg-white border-b border-gray-100 px-6 py-3 flex items-center gap-4 flex-shrink-0 shadow-sm z-10">
          <button onClick={() => setSidebarOpen(v => !v)} className="text-gray-400 hover:text-gray-700 transition">
            <Settings2 size={20} />
          </button>
          <div className="flex items-center gap-2 mr-4">
            <div className="w-7 h-7 rounded-md flex items-center justify-center text-white font-bold text-xs bg-gray-800">EA</div>
            <span className="font-bold text-navy text-sm hidden sm:block">Educator Analytics OS</span>
          </div>
          <div className="flex-1 max-w-md relative">
            <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input type="text" placeholder="Search system configs..." className="w-full pl-9 pr-4 py-2 text-sm rounded-lg border border-gray-200 bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-200 focus:border-gray-400 transition" />
          </div>
          <div className="flex-1" />
          <div className="flex items-center gap-2 cursor-pointer group">
            <div className="w-8 h-8 rounded-full bg-gray-800 flex items-center justify-center text-white font-bold text-xs">AD</div>
          </div>
        </header>

        <main className="flex-1 overflow-y-auto p-6 bg-gray-50">
          <div className="mb-6 animate-fade-in flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-navy">System Overview — April 2026</h1>
              <p className="text-gray-500 text-sm mt-1 flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-green-500"></span> All systems operational
              </p>
            </div>
            <button className="bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 flex items-center gap-2 shadow-sm">
              <Play size={14} /> Run Diagnostics
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
            {statCards.map((card, i) => (
              <div key={i} className={`card bg-white ${card.border} animate-fade-in`} style={{ animationDelay: `${i * 0.07}s` }}>
                <div className="flex items-center justify-between mb-3">
                  <p className="text-xs font-medium text-gray-500 uppercase tracking-wide">{card.label}</p>
                  <div className={`w-8 h-8 rounded-lg ${card.bg} flex items-center justify-center`}>
                    <card.icon size={16} color={card.color} />
                  </div>
                </div>
                <div className="flex items-end gap-2 mb-1">
                  <p className="text-2xl font-bold text-navy">{card.value}</p>
                  {card.label === 'System Health' && <div className="w-2.5 h-2.5 rounded-full bg-green-500 mb-2.5"></div>}
                </div>
                <p className="text-xs font-medium text-gray-500">{card.sub}</p>
              </div>
            ))}
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            {/* Left Column - Logs */}
            <div className="card animate-fade-in flex flex-col" style={{ animationDelay: '0.3s' }}>
              <div className="flex items-center justify-between mb-4 pb-2 border-b border-gray-100">
                <h2 className="font-semibold text-navy text-sm flex items-center gap-2">
                  <Terminal size={16} className="text-gray-400" /> Recent System Activity
                </h2>
                <button className="text-xs text-blue-600 hover:underline">View All</button>
              </div>
              <div className="space-y-4">
                {systemLogs.map((log, i) => (
                  <div key={i} className="flex gap-4 items-start">
                    <div className="mt-0.5">
                      <log.icon size={16} className={log.color} />
                    </div>
                    <div className="flex-1">
                      <p className="text-sm text-gray-700 font-medium">{log.msg}</p>
                      <p className="text-xs text-gray-400 mt-0.5 flex items-center gap-1">
                        <Clock size={12} /> {log.time}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Column - Actions */}
            <div className="card animate-fade-in flex flex-col" style={{ animationDelay: '0.38s' }}>
              <div className="flex items-center justify-between mb-4 pb-2 border-b border-gray-100">
                <h2 className="font-semibold text-navy text-sm">Quick Configuration Actions</h2>
                <Settings size={15} className="text-gray-400" />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 flex-1">
                {quickActions.map((action, i) => (
                  <button key={i} className="p-4 rounded-xl border border-gray-200 bg-white hover:border-gray-300 hover:shadow-md transition text-left flex flex-col items-start gap-3 group">
                    <div className="w-10 h-10 rounded-lg bg-gray-50 flex items-center justify-center text-gray-600 group-hover:bg-gray-800 group-hover:text-white transition-colors border border-gray-200">
                      <action.icon size={20} />
                    </div>
                    <span className="text-sm font-medium text-gray-700 group-hover:text-gray-900 transition-colors leading-snug">
                      {action.text}
                    </span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
